spring:
  application:
    name: sbm-tasks-service
  datasource:
    url: jdbc:mysql://localhost:3306/tasks-service
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/spring-boot-microservices-realm}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8181/realms/spring-boot-microservices-realm/protocol/openid-connect/certs}
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://admin:1234@${EUREKA_HOSTNAME:localhost}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0



#application:
#  rabbitmq:
#    exchange: ${RABBITMQ_EXCHANGE}
#    queues:
#      tasks:
#        queue: ${RABBITMQ_TASKS_QUEUE}
#        routing-key: ${RABBITMQ_TASKS_ROUTINGKEY}
#      delete-notification:
#        queue: ${RABBITMQ_DELETE_NOTIFICATION_QUEUE}
#        routing-key: ${RABBITMQ_DELETE_NOTIFICATION_ROUTINGKEY}
server:
  port: ${SERVER_PORT:8085}
